"""Controlled technical-field imports for any Cadastro category.

The import is intentionally stricter than the normal catalogue import: its
purpose is to update the technical values of an entire active category without
changing SKU identity, unit, active status, B.O.M. markers or operational
links.  A category-specific template is generated by the application and the
uploaded workbook must cover exactly the active SKU set for that category.
"""

from __future__ import annotations

import hashlib
import json
import re
from copy import deepcopy
from difflib import SequenceMatcher
from io import BytesIO
from typing import Any, Callable

from openpyxl import Workbook, load_workbook
from openpyxl.comments import Comment
from openpyxl.styles import Font, PatternFill

import excel_bancos


MAX_FILE_SIZE = 8 * 1024 * 1024
BASE_COLUMNS = ("COD", "CATEGORIA", "GRUPO")
FIELD_PREFIX = "CAMPO:"
META_SHEET = "_META"
TEMPLATE_FORMAT_VERSION = "2"

# PEÇAS BCO é mantida como um catálogo fechado: a planilha controlada pode
# usar estas grafias legadas, mas elas sempre convergem para opções canônicas
# já existentes. Qualquer outro valor desconhecido deve ser corrigido no XLSX
# em vez de ampliar silenciosamente o catálogo de produção.
STRICT_OPTION_CATEGORIES = {"cat_22_pecas_bco"}
STRICT_OPTION_ALIASES = {
    "cat_22_pecas_bco": {
        "cor": {
            "PRETO C CINZA": "PRETO/CINZA",
        },
        "fornecedor": {
            "ORIGINAL": "ORI",
        },
        "descritor_base": {
            "PEGA MAO": "PEGA MAO BCO",
        },
    },
}


def _text(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, float) and value.is_integer():
        return str(int(value))
    return str(value).strip()


def _header(value: Any) -> str:
    return excel_bancos.normalize_label(_text(value)).replace(" ", "")


def _group_code(value: Any) -> str:
    match = re.match(r"\s*(\d+)", _text(value))
    return match.group(1).zfill(2) if match else ""


def _field_header(field: dict[str, Any]) -> str:
    """Use the same field title shown to the Cadastro user in Excel."""
    return _text(field.get("label")) or field["key"]


def _display_value(field: dict[str, Any], values: Any) -> str:
    if not isinstance(values, list):
        values = [values] if values else []
    labels = [excel_bancos.option_label(value) or _text(value) for value in values if _text(value)]
    return " | ".join(labels)


def _field_fingerprint(category: dict[str, Any], fields: list[dict[str, Any]]) -> str:
    """Identify the exact category/field projection used by a template.

    Options are intentionally excluded: catalogue options may be added between
    download and upload.  Keys, labels and description semantics may not move,
    because accepting that kind of stale template can assign one column to a
    different technical field.
    """
    projection = {
        "category_key": _text(category.get("key")),
        "category_label": _text(category.get("label")),
        "fields": [
            {
                "key": _text(field.get("key")),
                "label": _field_header(field),
                "scope": _text(field.get("scope")),
                "selection_mode": _text(field.get("selection_mode")),
                "required": bool(field.get("required")),
                "free_text": bool(field.get("free_text")),
                "description_order": field.get("description_order"),
            }
            for field in fields
        ],
    }
    encoded = json.dumps(projection, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(encoded.encode("utf-8")).hexdigest()


def _write_template_metadata(
    workbook: Any,
    category: dict[str, Any],
    fields: list[dict[str, Any]],
) -> None:
    metadata = workbook.create_sheet(META_SHEET)
    for key, value in (
        ("template_format_version", TEMPLATE_FORMAT_VERSION),
        ("category_key", _text(category.get("key"))),
        ("category_label", _text(category.get("label"))),
        ("field_count", str(len(fields))),
        ("field_fingerprint", _field_fingerprint(category, fields)),
    ):
        metadata.append([key, value])
    metadata.sheet_state = "veryHidden"


def _validate_template_metadata(
    workbook: Any,
    category: dict[str, Any],
    fields: list[dict[str, Any]],
) -> None:
    if META_SHEET not in workbook.sheetnames:
        raise ValueError(
            "Template legado ou sem identificação estrutural. Baixe um novo template "
            "da categoria e transfira os valores antes de enviar; nenhuma alteração foi gravada."
        )
    metadata_sheet = workbook[META_SHEET]
    metadata = {
        _text(row[0]): _text(row[1])
        for row in metadata_sheet.iter_rows(min_col=1, max_col=2, values_only=True)
        if row and _text(row[0])
    }
    expected = {
        "template_format_version": TEMPLATE_FORMAT_VERSION,
        "category_key": _text(category.get("key")),
        "category_label": _text(category.get("label")),
        "field_count": str(len(fields)),
        "field_fingerprint": _field_fingerprint(category, fields),
    }
    divergences = [key for key, value in expected.items() if metadata.get(key) != value]
    if divergences:
        raise ValueError(
            "O catálogo da categoria mudou depois que este template foi baixado "
            f"({', '.join(divergences)}). Baixe um novo template; nenhuma alteração foi gravada."
        )


def build_template(
    category: dict[str, Any],
    fields: list[dict[str, Any]],
    active_rows: list[dict[str, Any]],
) -> bytes:
    """Generate the only supported input layout for a controlled update."""
    workbook = Workbook()
    worksheet = workbook.active
    worksheet.title = "CAMPOS_TECNICOS"
    headers = [*BASE_COLUMNS, *[_field_header(field) for field in fields]]
    worksheet.append(headers)
    header_fill = PatternFill("solid", fgColor="0F172A")
    for index, header in enumerate(headers, start=1):
        cell = worksheet.cell(1, index)
        cell.fill = header_fill
        cell.font = Font(color="FFFFFF", bold=True)
        if index > len(BASE_COLUMNS):
            field = fields[index - len(BASE_COLUMNS) - 1]
            mode = (
                "múltipla: separe valores por |"
                if field.get("selection_mode") == excel_bancos.SELECTION_MODE_MULTIPLA
                else "unitária"
            )
            cell.comment = Comment(
                f"{field.get('label') or field['key']}. Seleção {mode}. "
                "Valores novos com opção devem ser revisados antes do envio.",
                "Módulo Cadastro",
            )
        worksheet.column_dimensions[cell.column_letter].width = 24

    for row in sorted(active_rows, key=lambda value: _text(value.get("sku"))):
        form_values = row.get("form_values") if isinstance(row.get("form_values"), dict) else {}
        group_values = form_values.get(excel_bancos.PN_GROUP_FORM_KEY) or []
        group = _text(group_values[0] if isinstance(group_values, list) and group_values else "")
        worksheet.append(
            [
                _text(row.get("sku")),
                _text(category.get("label")),
                group,
                *[_display_value(field, form_values.get(field["key"])) for field in fields],
            ]
        )
    worksheet.freeze_panes = "A2"
    worksheet.auto_filter.ref = worksheet.dimensions
    worksheet.sheet_view.showGridLines = False
    instructions = workbook.create_sheet("INSTRUCOES")
    instructions.append(["ATUALIZAÇÃO CONTROLADA DE CAMPOS TÉCNICOS"])
    instructions.append([f"Categoria: {category.get('label')}"])
    instructions.append([
        "Não altere COD nem CATEGORIA. GRUPO é apenas informativo: o grupo já gravado no Cadastro será preservado."
    ])
    instructions.append(["Mantenha todos os SKUs ativos: o arquivo deve representar exatamente a categoria."])
    instructions.append(["As colunas técnicas usam os mesmos nomes de campos exibidos no Cadastro."])
    instructions.append(["Para seleção múltipla, separe os valores por |. Deixe vazio para limpar um campo."])
    instructions.column_dimensions["A"].width = 125
    instructions.sheet_view.showGridLines = False
    _write_template_metadata(workbook, category, fields)
    output = BytesIO()
    workbook.save(output)
    workbook.close()
    return output.getvalue()


def _split_values(raw: str) -> list[str]:
    return [part.strip() for part in re.split(r"\s*\|\s*", raw) if part.strip()]


def _matching_options(
    field: dict[str, Any],
    raw_value: str,
    category_key: str = "",
) -> list[str]:
    expected = excel_bancos.normalize_label(raw_value)
    alias = (
        STRICT_OPTION_ALIASES.get(category_key, {})
        .get(field.get("key") or "", {})
        .get(expected)
    )
    if alias:
        expected = excel_bancos.normalize_label(alias)
    matches = [
        option
        for option in field.get("options", [])
        if excel_bancos.normalize_label(excel_bancos.option_label(option)) == expected
    ]
    if not matches:
        compact = re.sub(r"[^A-Z0-9]+", "", expected)
        matches = [
            option
            for option in field.get("options", [])
            if re.sub(r"[^A-Z0-9]+", "", excel_bancos.normalize_label(excel_bancos.option_label(option))) == compact
        ]
    return matches


def _closest_option(field: dict[str, Any], raw_value: str) -> str:
    """Return the best display suggestion without accepting it implicitly."""
    expected = excel_bancos.normalize_label(raw_value)
    ranked: list[tuple[float, str]] = []
    for option in field.get("options", []):
        label = excel_bancos.option_label(option) or _text(option)
        score = SequenceMatcher(
            None,
            expected,
            excel_bancos.normalize_label(label),
        ).ratio()
        ranked.append((score, option))
    return max(ranked, default=(0.0, ""), key=lambda item: item[0])[1]


def _resolve_header_map(worksheet: Any, fields: list[dict[str, Any]]) -> tuple[int, dict[str, int]]:
    field_headers = {_header(_field_header(field)): field["key"] for field in fields}
    # Older downloaded templates used CAMPO:<chave>; keep them importable while
    # all newly downloaded templates show the field labels of the application.
    legacy_headers = {_header(f"{FIELD_PREFIX}{field['key']}"): field["key"] for field in fields}
    # Accept a unique display label too. This is also useful for controlled
    # spreadsheets generated before the template became category-specific.
    label_to_key: dict[str, str] = {}
    duplicates: set[str] = set()
    for field in fields:
        label = _header(field.get("label"))
        if not label:
            continue
        if label in label_to_key:
            duplicates.add(label)
        else:
            label_to_key[label] = field["key"]
    for label in duplicates:
        label_to_key.pop(label, None)

    for row_number in range(1, min(12, worksheet.max_row) + 1):
        raw_headers = {_header(cell.value): cell.column for cell in worksheet[row_number] if _header(cell.value)}
        if not {"COD", "CATEGORIA", "GRUPO"}.issubset(raw_headers):
            continue
        mapped = {"COD": raw_headers["COD"], "CATEGORIA": raw_headers["CATEGORIA"], "GRUPO": raw_headers["GRUPO"]}
        for normalized, field_key in field_headers.items():
            if normalized in raw_headers:
                mapped[field_key] = raw_headers[normalized]
        for normalized, field_key in legacy_headers.items():
            if field_key not in mapped and normalized in raw_headers:
                mapped[field_key] = raw_headers[normalized]
        for normalized, field_key in label_to_key.items():
            if field_key not in mapped and normalized in raw_headers:
                mapped[field_key] = raw_headers[normalized]
        missing = [field.get("label") or field["key"] for field in fields if field["key"] not in mapped]
        if missing:
            raise ValueError("A planilha não possui todos os campos técnicos da categoria: " + ", ".join(missing) + ".")
        return row_number, mapped
    raise ValueError("Não foi localizada a linha de cabeçalho do template de campos técnicos.")


def load_rows(content: bytes, category: dict[str, Any], fields: list[dict[str, Any]]) -> list[dict[str, Any]]:
    if not content:
        raise ValueError("O arquivo enviado está vazio.")
    if len(content) > MAX_FILE_SIZE:
        raise ValueError("A planilha excede o limite de 8 MB.")
    try:
        workbook = load_workbook(BytesIO(content), data_only=True, read_only=True)
    except Exception as exc:  # pragma: no cover
        raise ValueError("Não foi possível ler a planilha XLSX de campos técnicos.") from exc
    rows: list[dict[str, Any]] = []
    seen_skus: set[str] = set()
    try:
        _validate_template_metadata(workbook, category, fields)
        worksheet = workbook["CAMPOS_TECNICOS"] if "CAMPOS_TECNICOS" in workbook.sheetnames else workbook.active
        header_row, headers = _resolve_header_map(worksheet, fields)
        for row_number, source_row in enumerate(worksheet.iter_rows(min_row=header_row + 1, values_only=True), start=header_row + 1):
            sku = _text(source_row[headers["COD"] - 1])
            if not sku and not any(_text(value) for value in source_row):
                continue
            if not sku:
                raise ValueError(f"Linha {row_number}: COD é obrigatório.")
            if sku in seen_skus:
                raise ValueError(f"SKU duplicado na planilha: {sku}.")
            seen_skus.add(sku)
            informed_category = _text(source_row[headers["CATEGORIA"] - 1])
            if excel_bancos.normalize_label(informed_category) != excel_bancos.normalize_label(category.get("label")):
                raise ValueError(f"SKU {sku}: categoria informada deve ser {category.get('label')}.")
            rows.append(
                {
                    "sku": sku,
                    "group": _group_code(source_row[headers["GRUPO"] - 1]),
                    "values": {field["key"]: _text(source_row[headers[field["key"]] - 1]) for field in fields},
                }
            )
    finally:
        workbook.close()
    if not rows:
        raise ValueError("A planilha não contém SKUs para atualizar.")
    return rows


def missing_field_options(content: bytes, category: dict[str, Any], fields: list[dict[str, Any]]) -> dict[str, list[str]]:
    additions: dict[str, list[str]] = {}
    category_key = _text(category.get("key"))
    for source in load_rows(content, category, fields):
        for field in fields:
            if field.get("free_text"):
                continue
            for raw in _split_values(source["values"][field["key"]]):
                matches = _matching_options(field, raw, category_key)
                if len(matches) > 1:
                    raise ValueError(f"SKU {source['sku']}: valor {raw!r} é ambíguo no campo {field.get('label')}.")
                if not matches:
                    if category_key in STRICT_OPTION_CATEGORIES:
                        suggestion = _closest_option(field, raw)
                        detail = f" A opção mais próxima é {suggestion!r}." if suggestion else ""
                        raise ValueError(
                            f"SKU {source['sku']}: valor {raw!r} não existe no catálogo fechado "
                            f"do campo {field.get('label')}.{detail} Nenhuma opção foi criada."
                        )
                    pending = additions.setdefault(field["key"], [])
                    if excel_bancos.option_identity(raw) not in {excel_bancos.option_identity(value) for value in pending}:
                        pending.append(raw)
    return additions


def fields_with_pending_options(fields: list[dict[str, Any]], additions: dict[str, list[str]]) -> list[dict[str, Any]]:
    preview = deepcopy(fields)
    by_key = {field["key"]: field for field in preview}
    for field_key, values in additions.items():
        field = by_key[field_key]
        options = field.setdefault("options", [])
        next_code = 1
        for option in options:
            code = excel_bancos.option_code(option)
            if code.isdigit():
                next_code = max(next_code, int(code) + 1)
        for value in values:
            options.append(excel_bancos.normalize_option_text(f"{next_code}- {value}"))
            next_code += 1
    return preview


def _canonical_values(
    field: dict[str, Any],
    raw_value: str,
    sku: str,
    category_key: str = "",
) -> list[str]:
    values = _split_values(raw_value)
    if field.get("selection_mode") != excel_bancos.SELECTION_MODE_MULTIPLA and len(values) > 1:
        raise ValueError(f"SKU {sku}: o campo {field.get('label')} aceita apenas uma opção.")
    if field.get("free_text"):
        return values
    canonical: list[str] = []
    for value in values:
        matches = _matching_options(field, value, category_key)
        if len(matches) != 1:
            raise ValueError(f"SKU {sku}: valor {value!r} não possui correspondência única no campo {field.get('label')}.")
        canonical.append(matches[0])
    return canonical


def prepare_reconciliation(
    content: bytes,
    category: dict[str, Any],
    fields: list[dict[str, Any]],
    active_rows: list[dict[str, Any]],
    payload_builder: Callable[[dict[str, Any], dict[str, list[str]]], dict[str, Any]],
) -> dict[str, Any]:
    source_rows = load_rows(content, category, fields)
    rows_by_sku: dict[str, dict[str, Any]] = {}
    for registration in active_rows:
        sku = _text(registration.get("sku"))
        if sku in rows_by_sku:
            raise ValueError(f"Base possui mais de um cadastro ativo com o SKU {sku}.")
        if sku:
            rows_by_sku[sku] = registration
    source_skus = {row["sku"] for row in source_rows}
    absent_in_workbook = sorted(set(rows_by_sku) - source_skus)
    absent_in_database = sorted(source_skus - set(rows_by_sku))
    if absent_in_workbook or absent_in_database:
        details: list[str] = []
        if absent_in_workbook:
            details.append("ativos ausentes na planilha: " + ", ".join(absent_in_workbook[:12]))
        if absent_in_database:
            details.append("SKUs inexistentes/não ativos: " + ", ".join(absent_in_database[:12]))
        raise ValueError("A planilha deve representar exatamente os cadastros ativos da categoria (" + "; ".join(details) + "). Nenhuma alteração foi gravada.")

    payloads: list[dict[str, Any]] = []
    changed_skus: list[str] = []
    for source in source_rows:
        registration = rows_by_sku[source["sku"]]
        original = registration.get("form_values") if isinstance(registration.get("form_values"), dict) else {}
        selected = {
            field["key"]: _canonical_values(
                field,
                source["values"][field["key"]],
                source["sku"],
                _text(category.get("key")),
            )
            for field in fields
        }
        # The spreadsheet's GRUPO column is solely a visual cross-check.  A
        # technical-field reconciliation must never move an existing SKU to a
        # different group, even when a legacy template contains stale values.
        selected[excel_bancos.PN_GROUP_FORM_KEY] = original.get(excel_bancos.PN_GROUP_FORM_KEY) or []
        payload = payload_builder(registration, selected)
        payloads.append(payload)
        if any(payload.get(key) != registration.get(key) for key in ("descricao_primaria", "descricao_secundaria", "form_values", "field_values", "field_codes")):
            changed_skus.append(source["sku"])
    return {"total": len(source_rows), "payloads": payloads, "changed": len(changed_skus), "changed_skus": changed_skus}
